on: push

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ github.repository }}:latest
  lint:
    needs: image-build
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: |
          docker run --rm ${{ github.repository }}:latest npm run lint